# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 700)
        self.button_53 = QtWidgets.QPushButton(Form)
        self.button_53.setGeometry(QtCore.QRect(930, 550, 151, 71))
        self.button_53.setAutoDefault(False)
        self.button_53.setDefault(False)
        self.button_53.setFlat(False)
        self.button_53.setObjectName("button_53")
        self.label_53 = QtWidgets.QLabel(Form)
        self.label_53.setGeometry(QtCore.QRect(300, 40, 600, 450))
        self.label_53.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_53.setAutoFillBackground(False)
        self.label_53.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_53.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_53.setLineWidth(1)
        self.label_53.setText("")
        self.label_53.setScaledContents(True)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.label_55 = QtWidgets.QLabel(Form)
        self.label_55.setGeometry(QtCore.QRect(1100, 430, 80, 60))
        self.label_55.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_55.setText("")
        self.label_55.setScaledContents(True)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.label_54 = QtWidgets.QLabel(Form)
        self.label_54.setGeometry(QtCore.QRect(920, 370, 160, 120))
        self.label_54.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_54.setText("")
        self.label_54.setScaledContents(True)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.label_52 = QtWidgets.QLabel(Form)
        self.label_52.setGeometry(QtCore.QRect(120, 370, 160, 120))
        self.label_52.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_52.setText("")
        self.label_52.setScaledContents(True)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.label_51 = QtWidgets.QLabel(Form)
        self.label_51.setGeometry(QtCore.QRect(20, 430, 80, 60))
        self.label_51.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_51.setText("")
        self.label_51.setScaledContents(True)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.button_51 = QtWidgets.QPushButton(Form)
        self.button_51.setGeometry(QtCore.QRect(130, 560, 131, 71))
        self.button_51.setObjectName("button_51")
        self.button_52 = QtWidgets.QPushButton(Form)
        self.button_52.setGeometry(QtCore.QRect(500, 550, 200, 100))
        self.button_52.setObjectName("button_52")
        self.label_56 = QtWidgets.QLabel(Form)
        self.label_56.setGeometry(QtCore.QRect(20, 510, 72, 15))
        self.label_56.setText("")
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(Form)
        self.label_57.setGeometry(QtCore.QRect(170, 510, 72, 15))
        self.label_57.setText("")
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(Form)
        self.label_58.setGeometry(QtCore.QRect(560, 500, 81, 31))
        self.label_58.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_58.setText("")
        self.label_58.setScaledContents(False)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(Form)
        self.label_59.setGeometry(QtCore.QRect(960, 510, 72, 15))
        self.label_59.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_59.setText("")
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(Form)
        self.label_60.setGeometry(QtCore.QRect(1100, 510, 72, 15))
        self.label_60.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_60.setText("")
        self.label_60.setObjectName("label_60")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_53.setText(_translate("Form", "下一张"))
        self.button_51.setText(_translate("Form", "上一张"))
        self.button_52.setText(_translate("Form", "选择图片"))

